Sun Mar 18 08:37:16 EDT 2018 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
Sun Mar 18 08:37:24 EDT 2018 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Database 'Concert' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'Concert' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Concert' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Sun Mar 18 08:37:24 EDT 2018 Thread[DRDAConnThread_2,5,main] (DATABASE = Concert), (DRDAID = {1}), Database 'Concert' not found.
----------------------------------------------------------------
Sun Mar 18 08:37:45 EDT 2018:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0162-391d-0478-ffff9b8a3d46 
on database directory C:\Users\Jesus\Desktop\CTI289\Group_3\database\Concert with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_161/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b12
user.dir=C:\Program Files\Java\jdk1.8.0_161\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\Jesus\Desktop\CTI289\Group_3\database
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Sun Mar 18 08:38:20 EDT 2018:
Shutting down instance a816c00e-0162-391d-0478-ffff9b8a3d46 on database directory C:\Users\Jesus\Desktop\CTI289\Group_3\database\Concert with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Sun Mar 18 08:38:20 EDT 2018 Thread[DRDAConnThread_2,5,main] (DATABASE = Concert), (DRDAID = {3}), Database 'Concert' shutdown.
----------------------------------------------------------------
Sun Mar 18 08:39:07 EDT 2018:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 0ddd00a9-0162-391d-0478-ffff9b8a3d46 
on database directory C:\Users\Jesus\Desktop\CTI289\Group_3\database\Concert with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_161/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b12
user.dir=C:\Program Files\Java\jdk1.8.0_161\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\Jesus\Desktop\CTI289\Group_3\database
Database Class Loader started - derby.database.classpath=''
